id: P008001
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:21.142021
source_metadata:
  id: bdr:W1KG18406
  title: གཡེར་གཤོང་མཁན་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་བཀའ་འབུམ།
  author: ''
  volumes:
    e4e3ee2e157d48a4a221fbe06862ae1b:
      image_group_id: I1KG18443
      title: Volume 1 of g.yer gshong mkhan chen chos kyi rgyal po'i bka' 'bum/
      volume_number: 1
      total_pages: 782
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
