id: P008001
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18406
  title: གཡེར་གཤོང་མཁན་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་བཀའ་འབུམ།
  author: ''
  volumes:
    e4e3ee2e157d48a4a221fbe06862ae1b:
      image_group_id: I1KG18443
      title: Volume 1 of g.yer gshong mkhan chen chos kyi rgyal po'i bka' 'bum/
      volume_number: 1
      total_pages: 782
      base_file: v001.txt
ebook_metadata:
  title: གཡེར་གཤོང་མཁན་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་བཀའ་འབུམ།
  author: ''
  sku: P008001
  cover: cover.jpg
  layers:
  - pagination
