id: P008001
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18406
  title: གཡེར་གཤོང་མཁན་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་བཀའ་འབུམ།
  author: ''
  volumes:
    d5933c9bf97541beb12017a12103eb2c:
      image_group_id: I1KG18443
      title: ''
      volume_number: 1
      total_pages: 782
ebook_metadata:
  title: གཡེར་གཤོང་མཁན་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་བཀའ་འབུམ།
  author: ''
  sku: P008001
  cover: cover.jpg
  layers:
  - pagination
